title: Ignazio Aleo
logo: "/assets/images/logo.jpg"
description: Minimal blog of <a href="https://twitter.com/ignaleo">@ignazio</a>.<br>Motion Enthusiast, Co-Founder of <a href="https://twitter.com/moveshelf">@moveshelf</a>, Programmer, European.
theme: jekyll-theme-minimal